#ifndef TOMOBLOCKS16_H
#define TOMOBLOCKS16_H

// Generated by tools/ttf2enjin.py — do not edit by hand.
// Mono 1-bit GFXfont for enjin2::TextRenderer (type system #40).
#include "enjin2/graphics/gfxfont.h"

const uint8_t tomoBlocks16Bitmaps[] = {
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0x00,
  0x0F, 0xFF, 0xFF, 0xF0, 0xFF, 0xFC, 0x30, 0xC3, 0x0C, 0x30, 0xC3, 0x00,
};

const GFXglyph tomoBlocks16Glyphs[] = {
  // bitmapOffset, width, height, xAdvance, xOffset, yOffset
  {     0,   0,   0,   6,    0,    0 },   // 0x20 ' '
  {     0,   0,   0,   0,    0,    0 },   // 0x21 '!'
  {     0,   0,   0,   0,    0,    0 },   // 0x22 '"'
  {     0,   0,   0,   0,    0,    0 },   // 0x23 '#'
  {     0,   0,   0,   0,    0,    0 },   // 0x24 '$'
  {     0,   0,   0,   0,    0,    0 },   // 0x25 '%'
  {     0,   0,   0,   0,    0,    0 },   // 0x26 '&'
  {     0,   0,   0,   0,    0,    0 },   // 0x27 '''
  {     0,   0,   0,   0,    0,    0 },   // 0x28 '('
  {     0,   0,   0,   0,    0,    0 },   // 0x29 ')'
  {     0,   0,   0,   0,    0,    0 },   // 0x2A '*'
  {     0,   0,   0,   0,    0,    0 },   // 0x2B '+'
  {     0,   0,   0,   0,    0,    0 },   // 0x2C ','
  {     0,   0,   0,   0,    0,    0 },   // 0x2D '-'
  {     0,   0,   0,   0,    0,    0 },   // 0x2E '.'
  {     0,   0,   0,   0,    0,    0 },   // 0x2F '/'
  {     0,   0,   0,   0,    0,    0 },   // 0x30 '0'
  {     0,   0,   0,   0,    0,    0 },   // 0x31 '1'
  {     0,   0,   0,   0,    0,    0 },   // 0x32 '2'
  {     0,   0,   0,   0,    0,    0 },   // 0x33 '3'
  {     0,   0,   0,   0,    0,    0 },   // 0x34 '4'
  {     0,   0,   0,   0,    0,    0 },   // 0x35 '5'
  {     0,   0,   0,   0,    0,    0 },   // 0x36 '6'
  {     0,   0,   0,   0,    0,    0 },   // 0x37 '7'
  {     0,   0,   0,   0,    0,    0 },   // 0x38 '8'
  {     0,   0,   0,   0,    0,    0 },   // 0x39 '9'
  {     0,   0,   0,   0,    0,    0 },   // 0x3A ':'
  {     0,   0,   0,   0,    0,    0 },   // 0x3B ';'
  {     0,   0,   0,   0,    0,    0 },   // 0x3C '<'
  {     0,   0,   0,   0,    0,    0 },   // 0x3D '='
  {     0,   0,   0,   0,    0,    0 },   // 0x3E '>'
  {     0,   0,   0,   0,    0,    0 },   // 0x3F '?'
  {     0,   0,   0,   0,    0,    0 },   // 0x40 '@'
  {     0,   6,  10,   8,    0,  -10 },   // 0x41 'A'
  {     8,   6,  10,   8,    0,  -10 },   // 0x42 'B'
  {    16,   6,  10,   8,    0,  -10 },   // 0x43 'C'
};

const GFXfont tomoBlocks16 = {
  (uint8_t  *)tomoBlocks16Bitmaps,
  (GFXglyph *)tomoBlocks16Glyphs, 0x20, 0x43, 16 };

#endif // TOMOBLOCKS16_H
