#!/usr/bin/env python3
"""ttf2enjin.py — Convert a TTF/OTF into an enjin `GFXfont` C header.

A companion to `aseprite2enjin.py`, kept separate on purpose: the two tools
serve different input domains (pixel sprites vs. outline fonts) and share no
parsing. This one rasterises a font **monochrome (1-bit, no anti-aliasing) at
its native em size** and emits the Adafruit-GFX `GFXfont` byte layout that
`enjin2::TextRenderer` consumes unchanged — so the type-system renderer (#40)
gets its faces as plain applet data, integer-scale only (R4).

Rendering uses Pillow's FreeType backend: drawing onto a mode-'1' image is the
non-antialiased mono raster FreeType's `FT_LOAD_TARGET_MONO` produces, so no
grey coverage is spent (R4 has none to spend). Glyph metrics follow the
Adafruit `fontconvert` convention:

    xAdvance = round(advance width)
    xOffset  = ink left bearing (px from the pen)
    yOffset  = ink top relative to the baseline (negative above it)
    width/height = ink bounding box
    yAdvance = ascent + descent (line height)

Each glyph's bits are packed MSB-first and **byte-aligned at the glyph
boundary** (bitmapOffset counts bytes), matching `TextRenderer::drawChar`,
which restarts its bit cursor at each glyph's `bitmapOffset`.

Usage:
    ttf2enjin.py FONT.ttf --size 16 --name tomoDisplay16 -o tomo_display_16.h
"""

import argparse
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - environment guard
    sys.stderr.write("ttf2enjin: Pillow (PIL) is required — pip install pillow\n")
    raise


class Glyph:
    __slots__ = ("code", "width", "height", "x_advance", "x_offset",
                 "y_offset", "bits")

    def __init__(self, code, width, height, x_advance, x_offset, y_offset, bits):
        self.code = code
        self.width = width
        self.height = height
        self.x_advance = x_advance
        self.x_offset = x_offset
        self.y_offset = y_offset
        self.bits = bits  # list[list[int]] rows of 0/1, ink-cropped


def rasterize(font_path, size, first, last):
    """Rasterise [first, last] of `font_path` at `size` px, mono / no AA.

    Returns (glyphs, y_advance). `glyphs` is ordered by code point; each carries
    its ink bitmap (byte-unpacked rows) plus GFX metrics.
    """
    font = ImageFont.truetype(font_path, size)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    # Margin large enough for negative bearings / overshoot at this size.
    margin = size * 2
    canvas = size * 4

    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))

        # Draw onto a 1-bit image: freetype MONO, no anti-aliasing.
        img = Image.new("1", (canvas, canvas), 0)
        draw = ImageDraw.Draw(img)
        draw.text((margin, margin), ch, fill=1, font=font)
        bbox = img.getbbox()  # ink bounds, or None for an empty glyph (space)

        if bbox is None:
            glyphs.append(Glyph(code, 0, 0, advance, 0, 0, []))
            continue

        l, t, r, b = bbox
        width = r - l
        height = b - t
        x_offset = l - margin
        baseline = margin + ascent
        y_offset = t - baseline

        rows = []
        px = img.load()
        for y in range(t, b):
            row = [1 if px[x, y] else 0 for x in range(l, r)]
            rows.append(row)
        glyphs.append(Glyph(code, width, height, advance, x_offset, y_offset, rows))

    return glyphs, y_advance


def pack_bits(glyph):
    """Pack a glyph's ink rows MSB-first, byte-aligned at the glyph boundary."""
    out = bytearray()
    acc = 0
    nbits = 0
    for row in glyph.bits:
        for bit in row:
            acc = (acc << 1) | (bit & 1)
            nbits += 1
            if nbits == 8:
                out.append(acc)
                acc = 0
                nbits = 0
    if nbits:  # flush the final partial byte, padded low with zeros
        out.append(acc << (8 - nbits))
    return bytes(out)


def emit_header(glyphs, y_advance, name, first, last):
    """Render the C header text for a GFXfont named `name`."""
    guard = name.upper() + "_H"
    bitmap = bytearray()
    offsets = []
    for g in glyphs:
        offsets.append(len(bitmap))
        bitmap.extend(pack_bits(g))

    lines = []
    lines.append("#ifndef %s" % guard)
    lines.append("#define %s" % guard)
    lines.append("")
    lines.append("// Generated by tools/ttf2enjin.py — do not edit by hand.")
    lines.append("// Mono 1-bit GFXfont for enjin2::TextRenderer (type system #40).")
    lines.append('#include "enjin2/graphics/gfxfont.h"')
    lines.append("")

    # Bitmap array
    lines.append("const uint8_t %sBitmaps[] = {" % name)
    row = "  "
    for i, byte in enumerate(bitmap):
        row += "0x%02X, " % byte
        if (i % 12) == 11:
            lines.append(row.rstrip())
            row = "  "
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    lines.append("")

    # Glyph array
    lines.append("const GFXglyph %sGlyphs[] = {" % name)
    lines.append("  // bitmapOffset, width, height, xAdvance, xOffset, yOffset")
    for g, off in zip(glyphs, offsets):
        ch = g.code
        printable = chr(ch) if 0x20 < ch <= 0x7E else " "
        lines.append(
            "  { %5d, %3d, %3d, %3d, %4d, %4d },   // 0x%02X '%s'"
            % (off, g.width, g.height, g.x_advance, g.x_offset, g.y_offset, ch,
               printable if ch != 0x20 else " ")
        )
    lines.append("};")
    lines.append("")

    # Font struct
    lines.append("const GFXfont %s = {" % name)
    lines.append("  (uint8_t  *)%sBitmaps," % name)
    lines.append("  (GFXglyph *)%sGlyphs, 0x%02X, 0x%02X, %d };"
                 % (name, first, last, y_advance))
    lines.append("")
    lines.append("#endif // %s" % guard)
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Convert a TTF to an enjin GFXfont header.")
    ap.add_argument("font", help="input .ttf / .otf path")
    ap.add_argument("--size", type=int, required=True, help="pixel size (em height)")
    ap.add_argument("--name", required=True, help="C identifier for the GFXfont")
    ap.add_argument("--first", type=lambda s: int(s, 0), default=0x20,
                    help="first code point (default 0x20)")
    ap.add_argument("--last", type=lambda s: int(s, 0), default=0x7E,
                    help="last code point (default 0x7E)")
    ap.add_argument("-o", "--output", help="output header path (default: stdout)")
    args = ap.parse_args(argv)

    glyphs, y_advance = rasterize(args.font, args.size, args.first, args.last)
    header = emit_header(glyphs, y_advance, args.name, args.first, args.last)

    if args.output:
        with open(args.output, "w") as f:
            f.write(header)
        sys.stderr.write("ttf2enjin: wrote %s (%d glyphs)\n"
                         % (args.output, len(glyphs)))
    else:
        sys.stdout.write(header)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
